EjercicioPropedeutico/Controllers/ProductoController.cs
using System;
using System.Web.Mvc;
using EjercicioPropedeutico.Business;
using EjercicioPropedeutico.Etities;
using EjercicioPropedeutico.Models;
using System.Collections.Generic;
using System.Linq;

namespace EjercicioPropedeutico.Controllers
{
    public class ProductoController : Controller
    {
        public ActionResult Index(string busqueda)
        {
            ProductoBusiness ProductoBusiness = new ProductoBusiness();
            List<ProductoModel1> productos = new List<ProductoModel1>();
            var productoBase = ProductoBusiness.ObtenerTodos();
            productos = productoBase.Select(p =>
                     new ProductoModel1()
                     {
                         Id = p.id_producto,
                         IdProveedor = p.id_proveedor,
                         RazonSocialProveedor=p.razon_social,
                         Codigo = p.codigo,
                         Descripcion = p.descripcion,
                         Unidad = p.unidad,
                         Costo = p.costo
                     }).ToList();
            if(!string.IsNullOrWhiteSpace(busqueda))
            {
                productos = productos.Where(p=>p.Descripcion.Contains(busqueda)||
                    p.Codigo.Contains(busqueda)||
                    p.RazonSocialProveedor.Contains(busqueda)).ToList();
            }
            productos = productos.OrderBy(p =>p.RazonSocialProveedor).ToList();
            return View(productos);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            ViewBag.Proveedores = proveedoresBusiness.ObtenerTodos();
            return View();
        }
        [HttpPost]
        public ActionResult Add(ProductoModel1 model)
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            ViewBag.Proveedores = proveedoresBusiness.ObtenerTodos();
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }
            if (ModelState.IsValid)
            {
                Producto productoAgregar = new Producto()
                {
                    id_producto = model.Id,
                    id_proveedor = model.IdProveedor,
                    codigo = model.Codigo,
                    descripcion = model.Descripcion,
                    unidad = model.Unidad,
                    costo = model.Costo
                };
                new ProductoBusiness().Agregar(productoAgregar);
                ViewBag.Mensaje = "Se guardó correctamete";
                return View(new Models.ProductoModel1());
            }
            return View(model);
        }
        public ActionResult Edit(int id)
        {
            ProductoBusiness productoBusiness = new ProductoBusiness();
            Producto producto = productoBusiness.ObtenerPorId(id);
            ProductoModel1 model = new ProductoModel1()
            {
                Id = producto.id_producto,
                IdProveedor = producto.id_proveedor,
                Codigo = producto.codigo,
                Descripcion = producto.descripcion,
                Unidad = producto.unidad,
                Costo = producto.costo
            };
            return View(model);
        }
        public ActionResult Remove(int Id)
        {
            ProductoBusiness productoBusiness = new ProductoBusiness();
            productoBusiness.EliminarPorId(Id);
            TempData["Mensaje"] = "Eliminado correctamente";//aqui necesito agregar mi eliminacion del elemento
            return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult Edit(ProductoModel1 model)
        {
            if (ModelState.IsValid)
            {
                Etities.Producto productoAEditar = new Etities.Producto()
                {
                    id_producto = model.Id,
                    id_proveedor = model.IdProveedor,
                    codigo = model.Codigo,
                    descripcion = model.Descripcion,
                    unidad = model.Unidad,
                    costo = model.Costo
                };
                new ProductoBusiness().Edit(productoAEditar);
                TempData["Mensaje"] = "Se guardó correctamete";
                return RedirectToAction("Index");
            }
            return View(model);
        }

    }
}

EjercicioPropedeutico/Views/Producto/Add.cshtml
@model EjercicioPropedeutico.Models.ProductoModel1
@{
    ViewBag.Title = "Agregar Producto";
}
@Html.ActionLink("<---", "Index")
<h2>Agregar Producto</h2>
@ViewBag.Mensaje
@using (Html.BeginForm("Add", "Producto", FormMethod.Post))
{
    @Html.DisplayNameFor(m => m.IdProveedor) @Html.DropDownListFor(m => m.IdProveedor, new SelectList(ViewBag.Proveedores, "id_proveedor", "razon_social")) <br />
    @Html.DisplayNameFor(m => m.Codigo) @Html.TextBoxFor(m => m.Codigo)<br />
    @Html.DisplayNameFor(m => m.Descripcion) @Html.TextBoxFor(m => m.Descripcion) <br />
    @Html.DisplayNameFor(m => m.Unidad) @Html.TextBoxFor(m => m.Unidad) <br />
    @Html.DisplayNameFor(m => m.Costo) @Html.TextBoxFor(m => m.Costo, htmlAttributes: new { @placeholder = "Costo" })
    @Html.ValidationSummary();
    <button type="submit">Aceptar</button>
}

EjercicioPropedeutico/Views/Producto/Edit.cshtml
@model EjercicioPropedeutico.Models.ProductoModel1

@{
    ViewBag.Title = "Editar Producto jojo";
}
@Html.ActionLink("<---", "Index")
<h2>Editar Producto</h2>

@ViewBag.Mensaje
@using (Html.BeginForm("Edit", "Producto", FormMethod.Post))

{
    @Html.DisplayNameFor(m => m.IdProveedor)@Html.TextBoxFor(m => m.IdProveedor)<br />
    @Html.DisplayNameFor(m => m.Codigo) @Html.TextBoxFor(m => m.Codigo) <br />
    @Html.DisplayNameFor(m => m.Descripcion) @Html.TextBoxFor(m => m.Descripcion)<br />
    @Html.DisplayNameFor(m => m.Unidad) @Html.TextBoxFor(m => m.Unidad)<br />
    @Html.DisplayNameFor(m => m.Costo) @Html.TextBoxFor(m => m.Costo)
    @Html.ValidationSummary();
    <button type="submit"> Aceptar </button>
}

EjercicioPropedeutico/Views/Producto/Index.cshtml
@model List<EjercicioPropedeutico.Models.ProductoModel1>

@{
    ViewBag.Title = "IndexPRODUCTO";
}
<h2>Index</h2>
<h5>@TempData["Mensaje"]</h5>

<input type="text" name="busqueda" placeholder="Buscar..." />
<button type="submit">Buscar</button>
<br />
@Html.ActionLink("Nuevo", "Add", controllerName: "Proveedores", routeValues: null, htmlAttributes: new { @style = "color: green;font-weight: bold;" })
<table>
    <thead>
        <tr>
            <th colspan="6">Tabla de Productos </th>
            <th></th>
        </tr>
        <tr>
            <th>Id </th>
            <th>Proveedor</th>
            <th>Codigo</th>
            <th>Descripción</th>
            <th>Unidad</th>
            <th>Costo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (var m in Model)
            {
                <tr>
                    <td>@m.Id</td>
                    <td>@m.RazonSocialProveedor</td>
                    <td>@m.Codigo</td>
                    <td>@m.Descripcion</td>
                    <td>@m.Unidad</td>
                    <td>@m.Costo</td>
                    <td>@Html.ActionLink("Editar Elemento", "Edit", new { Id = m.Id })</td>
                    <td>@Html.ActionLink("Eliminar Elemento", "Remove", new { Id = m.Id })</td>
                </tr>
            }
        }
        
    </tbody>
</table>

EjercicioPropedeutico/Views/Producto/Remove.cshtml
@model EjercicioPropedeutico.Models.ProductoModel1
@{
    ViewBag.Title = "Eliminar PROVEEDOR";
}
@Html.ActionLink("<---", "Index")
<h2>Eliminar Elemento</h2>
@ViewBag.Mensaje
@using (Html.BeginForm("Remove", "Proveedores", FormMethod.Post))
{
    @Html.DisplayNameFor(m => m.IdProveedor) @Html.TextBoxFor(m => m.IdProveedor)<br />
    @Html.ValidationSummary();

    <button type="submit"></button>


}