EjercicioPropedeutico/Controllers/ProveedoresController.cs
using EjercicioPropedeutico.Business;
using EjercicioPropedeutico.Etities;
using EjercicioPropedeutico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace EjercicioPropedeutico.Controllers
{
    public class ProveedoresController : Controller
    {
        public ActionResult Index(string busqueda)
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            List<ProveedorModel> proveedores = new List<ProveedorModel>();
            var proveedoresBase = proveedoresBusiness.ObtenerTodos();
            proveedores = proveedoresBase.Select(p =>
                 new ProveedorModel()
                 {
                     Id = p.id_proveedor,
                     Codigo = p.codigo,
                     RazonSocialProveedor = p.razon_social,
                     RazonSocial = p.razon_social,
                     RFC = p.RFC
                 }).ToList();
            if (!string.IsNullOrWhiteSpace(busqueda))
            {
                proveedores = proveedores.Where(p => p.RazonSocialProveedor.Contains(busqueda) ||
                    p.Codigo.Contains(busqueda) ||
                    p.RazonSocialProveedor.Contains(busqueda)).ToList();
            }
            proveedores = proveedores.OrderBy(p => p.RazonSocialProveedor).ToList();
            return View(proveedores);
            //  return View(proveedores);
        }
        [HttpGet]
        public ActionResult Add()
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            ViewBag.Proveedores = proveedoresBusiness.ObtenerTodos();
            return View();
        }
        [HttpPost]
        public ActionResult Add(Models.ProveedorModel model)
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            ViewBag.Proveedores = proveedoresBusiness.ObtenerTodos();
            List<char> letrasPermitidas = new char[] { 'A', 'C', 'D', 'E', 'F' }.ToList();
            if (model == null)
            {
                throw new ArgumentNullException(nameof(model));
            }
            if (!letrasPermitidas.Contains(model.RFC.FirstOrDefault()))
            {
                ModelState.AddModelError("RFC", "Debe comenzar con la letra : A, C, D, E, F");
            }
            if (ModelState.IsValid)
            {

                //Etities.Proveedores proveedoresAgregar = new Etities.Proveedores()
                Proveedores proveedoresAgregar = new Proveedores()
                {
                    codigo = model.Codigo,
                    razon_social = model.RazonSocial,
                    RFC = model.RFC
                };
                new Business.ProveedoresBusiness().Agregar(proveedoresAgregar);
                ViewBag.Mensaje = "Se guardó correctamete";
                return View(new Models.ProveedorModel());
            }
            return View(model);
        }
        public ActionResult Edit(int Id)//comienza a editar
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            Proveedores proveedor = proveedoresBusiness.ObtenerPorId(Id);
            ProveedorModel model = new ProveedorModel()
            {
                Id = proveedor.id_proveedor,
                Codigo = proveedor.codigo,
                RazonSocial = proveedor.razon_social,
                RFC = proveedor.RFC
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(ProveedorModel model)
        {
            if (ModelState.IsValid)
            {
                Etities.Proveedores proveedorAEditar = new Etities.Proveedores()
                {
                    id_proveedor = model.Id,
                    codigo = model.Codigo,
                    razon_social = model.RazonSocial,
                    RFC = model.RFC
                };
                new ProveedoresBusiness().Edit(proveedorAEditar);
                TempData["Mensaje"] = "Se guardó correctamete";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public JsonResult Remove(int Id,bool forzar = false)
        {
            ProveedoresBusiness proveedoresBusiness = new ProveedoresBusiness();
            try
            {
                proveedoresBusiness.EliminarPorId(Id,forzar);
                TempData["Mensaje"] = "Eliminado Satisfactoriamente";//aqui necesito agregar mi eliminacion del elemento
                return Json(new { exito = true }, JsonRequestBehavior.AllowGet);
            }
            catch (IdNegativoException negativoException)
            {
                TempData["Error"] = "El id es negativo";
            }
            catch (Exception e)
            {
                TempData["Error"] = "Excepcio desconocida";
            }
            ResultadoElimiacion resultado = new ResultadoElimiacion();
            resultado.exito = false;
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ValidarTieneProductos(int Id)
        {
            ProductoBusiness productoBusiness = new ProductoBusiness();
            try
            {
                List<Etities.Producto> productos = productoBusiness.ObtenerPorProveedor(Id);
                if(productos.Any())
                {
                    return Json(new { exito = true, tiene = true, numeroProductos=productos.Count});
                }
                else
                {
                    return Json(new { exito = true, tiene = false });
                }
            }
            catch
            {
                return Json(new { exito = false });
            }
        }
    }
    public class ResultadoElimiacion
    {
        public bool exito { get; set; }
    }
}

EjercicioPropedeutico/Views/Proveedores/Add.cshtml
@model EjercicioPropedeutico.Models.ProveedorModel
@{
    ViewBag.Title = "Agregar Proveedor";
}
@Html.ActionLink("<---","Index")
<h2>Agregar</h2>
@ViewBag.Mensaje
@using (Html.BeginForm("Add", "Proveedores", FormMethod.Post))
{
    @Html.DisplayNameFor(m => m.Codigo) @Html.TextBoxFor(m => m.Codigo) <br />
    @Html.DisplayNameFor(m => m.RazonSocial) @Html.TextBoxFor(m => m.RazonSocial)<br />
    @Html.DisplayNameFor(m => m.RFC) @Html.TextBoxFor(m => m.RFC) @Html.ValidationMessageFor(m => m.RFC)
    @Html.ValidationSummary();
    <button type="submit">Aceptar</button>
}

EjercicioPropedeutico/Views/Proveedores/Edit.cshtml
@model EjercicioPropedeutico.Models.ProveedorModel

@{
    ViewBag.Title = "Editar Proveedor";
}

<h2>Editar Proveedor</h2>

@ViewBag.Mensaje
@using (Html.BeginForm("Edit", "Proveedores", FormMethod.Post))
{
    @Html.DisplayNameFor(m => m.Codigo) @Html.TextBoxFor(m => m.Codigo) <br />
    @Html.DisplayNameFor(m => m.RazonSocial) @Html.TextBoxFor(m => m.RazonSocial)<br />
    @Html.DisplayNameFor(m => m.RFC) @Html.TextBoxFor(m => m.RFC) @Html.ValidationMessageFor(m => m.RFC)
    @Html.ValidationSummary();
    <button type="submit">Aceptar</button>
}

EjercicioPropedeutico/Views/Proveedores/Index.cshtml
@model List<EjercicioPropedeutico.Models.ProveedorModel>
@{

    ViewBag.Title = "Ejemplo de index PROVEEDOR";
}
@section styles
{
<style>
    .like-link {
        color:dodgerblue;
        cursor:pointer;
    }
        .like-link:hover {
            color: #0056b3;
            text-decoration: underline;
        }
    #mensaje-informacion{
        color:cornflowerblue;
    }
</style>
}
<h2>RFACIL Facturación Electronica</h2>
<h5 id="mensaje-informacion"></h5>
<h5 style="color:red;" id="mensaje-error"></h5>
<input type="text" name="busqueda" placeholder="Buscar..." />
<button type="submit">Buscar</button>
<br />
@Html.ActionLink("Nuevo", "Add", controllerName: "Proveedores", routeValues: null, htmlAttributes: new { @style = "color: green;font-weight: bold;" })
<table>
    <thead>
        <tr>
            <th colspan="4">Tabla de Proveedores</th>
            <th></th>
        </tr>
        <tr>
            <th>Id</th>
            <th>Codigo</th>
            <th>Razón Social</th>
            <th>RFC</th>
            <th></th>
        </tr>
        @if (Model != null)
        {
            foreach (var m in Model)
            {
                <tr>
                    <td>@m.Id</td>
                    <td>@m.RazonSocialProveedor</td>
                    <td>@m.Codigo</td>
                    <td>@m.RazonSocial</td>
                    <td>@m.RFC</td>
                    <td>@Html.ActionLink("Editar Elemento", "Edit", new { Id = m.Id })</td>
                    <td><span onclick="ValidarYEliminarProveedor(this)" data-id="@m.Id" class="like-link">Eliminar Elemento</span></td>
                </tr>
            }
        }
    </thead>
</table>

<div id="myModal" class="modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Error al eliminar</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>El proveedor seleccionado tiene <span style="color:chartreuse" id="numero-productos"></span> productos<br />Desea elimiarlos</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="eliminar-forzado">Si</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cacelar</button>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        var ultimoSeleccionado;
        function ValidarYEliminarProveedor(elemento) {
            var idElemento = elemento.getAttribute('data-id');
            $.ajax(
                {
                    url: "@Url.Action("ValidarTieneProductos")",
                    data: { Id: idElemento },
                    type: 'post',
                    dataType: 'json',
                    success: function (data) {
                        debugger;
                        if (data.exito) {
                            if (data.tiene) {
                                $("#numero-productos").text(data.numeroProductos);
                                $('#myModal').modal('show');
                                ultimoSeleccionado = elemento;
                            }
                            else {
                                EliminarProveedor(elemento);
                            }
                        }
                        else {
                            $("#mensaje-error").text('No se pudo completar la accion');
                        }
                    }
                });
        }
        function EliminarProveedor(elemento, forzar) {
            debugger;
            forzar = forzar || false;
            var idElemento = elemento.getAttribute('data-id');
            $.ajax(
            {
                url: '@Url.Action("Remove")',
                data: { Id: idElemento,forzar:forzar },
                type: 'post',
                dataType: 'json',
                success: function (data) {
                    if (data.exito) {
                        $("#mensaje-informacion").text('Todo salio bien')
                        window.location = window.location;
                    }
                    else {
                        $("#mensaje-error").text('Ocurio un error');
                        $('#myModal').modal('hide');
                    }
                }
            });
        }
        document.getElementById('eliminar-forzado').addEventListener('click', function () {
            EliminarProveedor(ultimoSeleccionado, true);
        });
    </script>
}

EjercicioPropedeutico/Views/Proveedores/Remove.cshtml
@model EjercicioPropedeutico.Models.ProductoModel1
@{
    ViewBag.Title = "Eliminar PRODUCTO";
}

<h2>Eliminar Elemento</h2>
@ViewBag.Mensaje
@using (Html.BeginForm("Remove", "Proveedores", FormMethod.Post))
{
    @Html.DisplayNameFor(m => m.IdProveedor) @Html.TextBoxFor(m => m.IdProveedor)<br />
    @Html.ValidationSummary();

    <button type="submit"></button>


}